"""empty message

Revision ID: 8fedb613a714
Revises: 
Create Date: 2023-06-24 14:34:17.011547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fedb613a714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summoner_model',
    sa.Column('puuid', sa.VARCHAR(length=100), nullable=False),
    sa.Column('region', sa.VARCHAR(length=10), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('icon_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_table('version_model',
    sa.Column('id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champion_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_model',
    sa.Column('id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('continent', sa.VARCHAR(length=10), nullable=True),
    sa.Column('creation', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('endedEarlySurrender', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perkicon_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=10), nullable=True),
    sa.Column('binary', mysql.MEDIUMBLOB(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profileicon_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rune_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('shortDesc', sa.TEXT(), nullable=True),
    sa.Column('longDesc', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shard_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shortDesc', sa.TEXT(), nullable=True),
    sa.Column('longDesc', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprite_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=10), nullable=True),
    sa.Column('binary', mysql.MEDIUMBLOB(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_model',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_model',
    sa.Column('id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('match_id', sa.VARCHAR(length=30), nullable=True),
    sa.Column('key', sa.INTEGER(), nullable=True),
    sa.Column('team_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('puuid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('summoner_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('profileicon_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('champion_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('champion_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('summoner_spell1_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('summoner_spell1_casts', sa.Integer(), nullable=True),
    sa.Column('summoner_spell2_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('summoner_spell2_casts', sa.Integer(), nullable=True),
    sa.Column('spell1_casts', sa.Integer(), nullable=True),
    sa.Column('spell2_casts', sa.Integer(), nullable=True),
    sa.Column('spell3_casts', sa.Integer(), nullable=True),
    sa.Column('spell4_casts', sa.Integer(), nullable=True),
    sa.Column('main_perk1_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('main_perk1_vars', sa.JSON(), nullable=True),
    sa.Column('main_perk2_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('main_perk2_vars', sa.JSON(), nullable=True),
    sa.Column('main_perk3_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('main_perk3_vars', sa.JSON(), nullable=True),
    sa.Column('main_perk4_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('main_perk4_vars', sa.JSON(), nullable=True),
    sa.Column('sub_perk1_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('sub_perk1_vars', sa.JSON(), nullable=True),
    sa.Column('sub_perk2_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('sub_perk2_vars', sa.JSON(), nullable=True),
    sa.Column('shard1_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('shard2_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('shard3_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item0_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item1_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item2_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item3_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item4_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item5_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('item6_key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('win', sa.BOOLEAN(), nullable=True),
    sa.Column('kills', sa.INTEGER(), nullable=True),
    sa.Column('deaths', sa.INTEGER(), nullable=True),
    sa.Column('assists', sa.INTEGER(), nullable=True),
    sa.Column('gold_earned', sa.INTEGER(), nullable=True),
    sa.Column('gold_spent', sa.INTEGER(), nullable=True),
    sa.Column('items_purchased', sa.INTEGER(), nullable=True),
    sa.Column('champion_level', sa.INTEGER(), nullable=True),
    sa.Column('champion_transform', sa.INTEGER(), nullable=True),
    sa.Column('champion_experience', sa.INTEGER(), nullable=True),
    sa.Column('total_damage_dealt', sa.INTEGER(), nullable=True),
    sa.Column('total_damage_dealt_to_champions', sa.INTEGER(), nullable=True),
    sa.Column('true_damage_dealt_to_champions', sa.INTEGER(), nullable=True),
    sa.Column('magic_damage_dealt_to_champions', sa.INTEGER(), nullable=True),
    sa.Column('physical_damage_dealt_to_champions', sa.INTEGER(), nullable=True),
    sa.Column('total_damage_taken', sa.INTEGER(), nullable=True),
    sa.Column('true_damage_taken', sa.INTEGER(), nullable=True),
    sa.Column('magic_damage_taken', sa.INTEGER(), nullable=True),
    sa.Column('physical_damage_taken', sa.INTEGER(), nullable=True),
    sa.Column('damage_self_mitigated', sa.INTEGER(), nullable=True),
    sa.Column('time_CCing', sa.INTEGER(), nullable=True),
    sa.Column('total_time_CC_dealt', sa.INTEGER(), nullable=True),
    sa.Column('total_heal', sa.INTEGER(), nullable=True),
    sa.Column('total_heals_on_teammates', sa.INTEGER(), nullable=True),
    sa.Column('total_shielded_on_teammates', sa.INTEGER(), nullable=True),
    sa.Column('time_played', sa.INTEGER(), nullable=True),
    sa.Column('turrets_lost', sa.INTEGER(), nullable=True),
    sa.Column('inhibitors_lost', sa.INTEGER(), nullable=True),
    sa.Column('double_kills', sa.INTEGER(), nullable=True),
    sa.Column('triple_kills', sa.INTEGER(), nullable=True),
    sa.Column('quadra_kills', sa.INTEGER(), nullable=True),
    sa.Column('penta_kills', sa.INTEGER(), nullable=True),
    sa.Column('killing_sprees', sa.INTEGER(), nullable=True),
    sa.Column('largest_multi_kill', sa.INTEGER(), nullable=True),
    sa.Column('largest_killing_spree', sa.INTEGER(), nullable=True),
    sa.Column('bounty_level', sa.INTEGER(), nullable=True),
    sa.Column('total_minions_killed', sa.INTEGER(), nullable=True),
    sa.Column('longest_time_spent_living', sa.INTEGER(), nullable=True),
    sa.Column('total_time_spent_dead', sa.INTEGER(), nullable=True),
    sa.Column('challenges', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_model',
    sa.Column('id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('match_id', sa.VARCHAR(length=30), nullable=True),
    sa.Column('key', sa.VARCHAR(length=5), nullable=True),
    sa.Column('win', sa.BOOLEAN(), nullable=True),
    sa.Column('first_blood', sa.BOOLEAN(), nullable=True),
    sa.Column('first_turret_kill', sa.BOOLEAN(), nullable=True),
    sa.Column('turret_kills', sa.INTEGER(), nullable=True),
    sa.Column('inhibitor_kills', sa.INTEGER(), nullable=True),
    sa.Column('total_damage_dealt_to_champions', sa.INTEGER(), nullable=True),
    sa.Column('total_damage_taken', sa.INTEGER(), nullable=True),
    sa.Column('kills', sa.INTEGER(), nullable=True),
    sa.Column('deaths', sa.INTEGER(), nullable=True),
    sa.Column('assists', sa.INTEGER(), nullable=True),
    sa.Column('gold_earned', sa.INTEGER(), nullable=True),
    sa.Column('gold_spent', sa.INTEGER(), nullable=True),
    sa.Column('time_CCing', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_model')
    op.drop_table('participant_model')
    op.drop_table('style_model')
    op.drop_table('sprite_model')
    op.drop_table('spell_model')
    op.drop_table('shard_model')
    op.drop_table('rune_model')
    op.drop_table('profileicon_model')
    op.drop_table('perkicon_model')
    op.drop_table('match_model')
    op.drop_table('item_model')
    op.drop_table('champion_model')
    op.drop_table('version_model')
    op.drop_table('summoner_model')
    # ### end Alembic commands ###
